services:
  server:
    container_name: all-debrid-client-astro-dev

    command: npm run dev -- --host

    environment:
      - NODE_ENV=${NODE_ENV}

    volumes:
      - .:/var/app
      - /var/app/node_modules
