services:
  server:
    container_name: all-debrid-client-astro
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        - PORT=${PORT}
        - PUBLIC_MOTRIX=${PUBLIC_MOTRIX}
        - PUBLIC_GOPEED=${PUBLIC_GOPEED}
        - PUBLIC_DS=${PUBLIC_DS}
        - NODE_ENV=${NODE_ENV}
        - PUBLIC_TMDB=${PUBLIC_TMDB}
    environment:
      - PORT=${PORT}
      - SECRET_API_ALLDEBRID_LOCAL=${SECRET_API_ALLDEBRID_LOCAL}
      - SECRET_OFFICIAL_ALLDEBRID_API=${SECRET_OFFICIAL_ALLDEBRID_API}
      - SECRET_ALLDEBRID_TOKEN=${SECRET_ALLDEBRID_TOKEN}
      - PUBLIC_MOTRIX=${PUBLIC_MOTRIX}
      - PUBLIC_DS=${PUBLIC_DS}
      - PUBLIC_GOPEED=${PUBLIC_GOPEED}
      - SECRET_API_PLEX_LOCAL=${SECRET_API_PLEX_LOCAL}
      - SECRET_PLEX_TOKEN=${SECRET_PLEX_TOKEN}
      - SECRET_PLEX_ENDPOINT=${SECRET_PLEX_ENDPOINT}
      - SECRET_NAS_ENDPOINT=${SECRET_NAS_ENDPOINT}
      - SECRET_NAS_ACCOUNT=${SECRET_NAS_ACCOUNT}
      - SECRET_NAS_PWD=${SECRET_NAS_PWD}
      - SECRET_GOPEED_TOKEN=${SECRET_GOPEED_TOKEN}
      - SECRET_PROWLARR_ENDPOINT=${SECRET_PROWLARR_ENDPOINT}
      - SECRET_PROWLARR_API_KEY=${SECRET_PROWLARR_API_KEY}
      - SECRET_SONARR_ENDPOINT=${SECRET_SONARR_ENDPOINT}
      - SECRET_SONARR_API_KEY=${SECRET_SONARR_API_KEY}
      - SECRET_RADARR_ENDPOINT=${SECRET_RADARR_ENDPOINT}
      - SECRET_RADARR_API_KEY=${SECRET_RADARR_API_KEY}
      - SECRET_TMDB_API_KEY=${SECRET_TMDB_API_KEY}
      - PUBLIC_TMDB=${PUBLIC_TMDB}
    working_dir: /var/app
    user: root
    ports:
      - "${PORT}:${PORT}"
