name: cd_all_debrid_client_astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    env:
      PORT: ${{ secrets.PORT }}
      SECRET_API_ALLDEBRID_LOCAL: ${{ secrets.SECRET_API_ALLDEBRID_LOCAL }}
      SECRET_OFFICIAL_ALLDEBRID_API: ${{ secrets.SECRET_OFFICIAL_ALLDEBRID_API }}
      SECRET_ALLDEBRID_TOKEN: ${{ secrets.SECRET_ALLDEBRID_TOKEN }}
      PUBLIC_MOTRIX: ${{ secrets.PUBLIC_MOTRIX }}
      PUBLIC_DS: ${{ secrets.PUBLIC_DS }}
      SECRET_API_PLEX_LOCAL: ${{ secrets.SECRET_API_PLEX_LOCAL }}
      SECRET_PLEX_TOKEN: ${{ secrets.SECRET_PLEX_TOKEN }}
      SECRET_PLEX_ENDPOINT: ${{ secrets.SECRET_PLEX_ENDPOINT }}
      SECRET_NAS_ENDPOINT: ${{ secrets.SECRET_NAS_ENDPOINT }}
      SECRET_NAS_ACCOUNT: ${{ secrets.SECRET_NAS_ACCOUNT }}
      SECRET_NAS_PWD: ${{ secrets.SECRET_NAS_PWD }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      SECRET_GOPEED_TOKEN: ${{ secrets.SECRET_GOPEED_TOKEN }}
      PUBLIC_GOPEED: ${{ secrets.PUBLIC_GOPEED }}
      SECRET_PROWLARR_API_KEY: ${{ secrets.SECRET_PROWLARR_API_KEY }}
      SECRET_PROWLARR_ENDPOINT: ${{ secrets.SECRET_PROWLARR_ENDPOINT }}
      SECRET_SONARR_ENDPOINT: ${{ secrets.SECRET_SONARR_ENDPOINT }}
      SECRET_SONARR_API_KEY: ${{ secrets.SECRET_SONARR_API_KEY }}
      SECRET_RADARR_ENDPOINT: ${{ secrets.SECRET_RADARR_ENDPOINT }}
      SECRET_RADARR_API_KEY: ${{ secrets.SECRET_RADARR_API_KEY }}
      SECRET_TMDB_API_KEY: ${{ secrets.SECRET_TMDB_API_KEY }}
      PUBLIC_TMDB: ${{ secrets.PUBLIC_TMDB }}

    steps:
      - name: 📦 Cloner le dépôt
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 🛑 Stop des conteneurs (si en cours)
        run: docker compose down || true
        working-directory: /var/app

      - name: 🧹 Nettoyer /var/app et recopier les sources
        run: |
          sudo rm -rf /var/app/*
          sudo cp -a $(pwd)/. /var/app

      - name: 🛠️ Build et démarrage de l'image Docker
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.prod.yml \
            up --build -d
        working-directory: /var/app

      - name: 🧪 Logs du conteneur (si échec)
        if: failure()
        run: docker logs $(docker ps -alq)
        working-directory: /var/app
